### PR TITLE
Update develop branch with latest schema.

### PR DESCRIPTION
**Pull request by dancgray**
!!Do not review yet as we may be moving this components global ariaLabels to this schema!!

### CODE REVIEW

**Comment by taylortom** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by dancgray** [comment]
Should I remove it then?

**Comment by oliverfoster** [comment]
yea, and from the template

**Comment by taylortom** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
